version: "3"
services:
  nginx:
    image: gihyodocker/nginx-proxy:latest
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role != manager
    environment:
      backend_hosts: "helloserver:8080"
    depends_on:
      - api
    networks:
      - ch03
  api:
    image: registry:5000/helloserver:1.1
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role != manager
    networks:
      - ch03

networks:
  ch03:
    external: true
