version: "3"

services:
  master:
    build:
      context: ./
      dockerfile: master/Dockerfile
    image: gngsn/tododb-master:latest
    environment:
      MYSQL_ROOT_PASSWORD: gngsn
      MYSQL_DATABASE: tododb
      MYSQL_USER: gngsn
      MYSQL_PASSWORD: gngsn
      MYSQL_MASTER: "true"
    networks:
      - todoapp

  slave:
    build:
      context: ./
      dockerfile: slave/Dockerfile
    image: gngsn/tododb-slave:latest
    depends_on:
      - master
    environment:
      MYSQL_MASTER_HOST: gngsn
      MYSQL_ROOT_PASSWORD: gngsn
      MYSQL_DATABASE: tododb
      MYSQL_USER: gngsn
      MYSQL_PASSWORD: gngsn
      MYSQL_REPL_USER: repl
      MYSQL_REPL_PASSWORD: gngsn
    networks:
      - todoapp

networks:
  todoapp:
    external: true
