version: "3"

services:
  master:
    image: registry:5000/gngsn/tododb:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
    environment:
      MYSQL_ROOT_PASSWORD: gngsn
      MYSQL_DATABASE: tododb
      MYSQL_USER: gngsn
      MYSQL_PASSWORD: gngsn
      MYSQL_MASTER: "true"
    command:
      - bash
    networks:
      - todoapp

  slave:
    image: registry:5000/gngsn/tododb:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    depends_on:
      - master
    environment:
      MYSQL_MASTER_HOST: gngsn
      MYSQL_ROOT_PASSWORD: gngsn
      MYSQL_DATABASE: tododb
      MYSQL_USER: gngsn
      MYSQL_PASSWORD: gngsn
      MYSQL_REPL_USER: repl
      MYSQL_REPL_PASSWORD: gngsn
    networks:
      - todoapp

networks:
  todoapp:
    external: true



# docker container run -d --rm --name mysql -e "MYSQL_ROOT_PASSWORD=gngsn"-e "MYSQL_DATABASE=tododb" -e "MYSQL_USER=gngsn" -e "MYSQL_PASSWORD=gngsn" -e "MYSQL_MASTER=true"  mysql:5.7   \\\ --volumes-from mysql-data \\n
#  docker container run -d --name tododb -e "MYSQL_ROOT_PASSWORD=gngsn"-e "MYSQL_DATABASE=tododb" -e "MYSQL_USER=gngsn" -e "MYSQL_PASSWORD=gngsn" -e "MYSQL_MASTER=true" localhost:5000/gngsn/tododb:latest
#  docker container run -d -e MYSQL_ROOT_PASSWORD=gngsn -e MYSQL_DATABASE=tododb -e MYSQL_USER=gngsn -e MYSQL_PASSWORD=gngsn -e MYSQL_MASTER=true --name tododb localhost:5000/gngsn/tododb:latest
